### ISSUE TITLE
:bug: Meeting schedule calendar is not publicly viewable

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/meta#419] opened 2021-07-04 17:36 UTC
I think the calendar permissions aren't configured to allow viewing it to unauthorized users:

![image](https://user-images.githubusercontent.com/2069677/124394275-1d395580-dcff-11eb-8519-a8c2f89e83d4.png)

![image](https://user-images.githubusercontent.com/2069677/124394265-14488400-dcff-11eb-809b-56f2081e4139.png)

**Comment by choldgraf** [comment] 2021-07-04 18:01
Thanks for catching this - we discussed it a bit too in the meeting and I have an item to look it up. I need to figure out how to make that calendar public.

**Comment by akhmerov** [comment] 2021-07-04 18:10
In the left sidebar select calendar options, then settings and sharing, then make available to public.

![image](https://user-images.githubusercontent.com/2069677/124395317-bbc7b580-dd03-11eb-8c5d-fc9f68dd29c0.png)


![image](https://user-images.githubusercontent.com/2069677/124395300-9c308d00-dd03-11eb-8936-0e1c085ad497.png)

**Comment by choldgraf** [comment] 2021-07-04 18:12
@akhmerov actually the problem is that the calendar is somehow not editable by myself for permissions, I have no idea why and google calendar confuses the heck outta me, so I think I just need to create a new one from scratch haha

**Comment by choldgraf** [comment] 2021-07-05 17:19
I think this is fixed by #420

**Closed by choldgraf** 2021-07-05 17:19 UTC
